---
services:
  chainui:
    # Uncomment the following lines to build the image locally
    # build:
    #   context: .
    #   dockerfile: "./Dockerfile"
    # image: chainui
    image: khulnasoft/chainui:latest
    restart: unless-stopped
    ports:
      - "3000:80"
